<a href="https://colab.research.google.com/github/Hartuty/Machinelearning/blob/master/SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from numpy.linalg import svd
#Singular Value Decomposition

In [2]:
A = np.array([[1,2,3],[2,3,4]])


array([[1, 2, 3],
       [2, 3, 4]])

In [6]:
U, S, VT=svd(A)
print(VT)

[[-0.33809817 -0.55064932 -0.76320047]
 [ 0.84795222  0.17354729 -0.50085764]
 [ 0.40824829 -0.81649658  0.40824829]]
